[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# cargo watch -x check -x test -x run
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }